In [5]:
# (0)
# importing required libraries
import numpy as np
import sys

# (1)
# taking inputs
# creating matrices
# validating the inputs

n = int(input('Enter the size of the matrix \t'))
X = np.zeros(n)
Y = np.zeros(n)

print('Enter the entries in a single line separated by a space')
entries = list(map(float, input().split()))
G = np.array(entries).reshape(n, n+1)

A = np.delete(G,n,1)
detA = np.linalg.det(A)
if  np.absolute(detA) < 0.00001 :
    sys.exit('This set of equations are indeterminant')
        
# (2)
# Scaling the matrix

AbsA = np.absolute(A)
scal = np.amax(AbsA, 1)

for i in range(n):
    for j in range(n+1):
        G[i,j] = G[i,j]/scal[i]
        
# (3)
# Partial Pivoting along coloumns

p = np.argmax(AbsA, 0)
for i in range(n):
    if p[i] > i:
        G[[i,p[i]]] = G[[p[i],i]]
        
# (4)
# Getting the new A and B matrices from G so that we can avoid Permutation matrix

A1 = G[0:n,0:n]
B1 = G[0:n,n:n+1]

# (5)
# (Decompoosing the matrix A1 into l and U)
# (Do-Little so so conv to U and get L)

L = np.identity(n, dtype = float)
for i in range(n-1):
    for j in range(1+i,n):
        factor = A1[j,i]/A1[i,i]
        L[j,i] = factor
        for k in range(1+i,n):
            A1[j,k] = A1[j,k] - factor*A1[i,k]
U = np.triu(A1)

# (6)
# (Back substitution twice once for LY = B1 then Y = UX

L1 = np.concatenate((L,B1), axis=1)    # for lower traingular matrix
print(L1)
for i in range(n):
    Y[i] = L1[i,n]
    for j in range(i-1,-1,-1):
        Y[i] =Y[i] - L1[i,j]*Y[j]
    Y[i] = Y[i]/L1[i,i]

Y1 = np.reshape(Y, (n, 1))
U1 = np.concatenate((U,Y1), axis=1)    # for upper traingular matrix
for i in range(n-1,-1,-1):
    X[i] = U1[i,n]
    for j in range(i+1,n):
        X[i] =X[i] - U1[i,j]*X[j]
    X[i] = X[i]/U1[i,i]

# (7)
# Displaying Solution

print('The solution vector is:')
for i in range(n):
    print('X[%d] =%0.4f' %(i,X[i]),'\t')

Enter the size of the matrix 	3
Enter the entries of augmented matrix in a single line separated by a space
1 -2 3 7 2 1 1 4 -3 2 -2 -10
[[-3.33333333]
 [ 2.        ]
 [ 2.33333333]]
[[ 1.          0.          0.         -3.33333333]
 [-1.          1.          0.          2.        ]
 [-0.33333333 -0.38095238  1.          2.33333333]]
[-3.33333333 -1.33333333  0.71428571]
[[-3.33333333]
 [-1.33333333]
 [ 0.71428571]]
[ 2. -1.  1.]
